version: '3'
services:
    postgres:
        image: postgres:16.0-alpine3.18
        container_name: postgres
        ports:
            - '6500:5432'
        volumes:
            - progresDB:/data/postgres
        env_file:
            - ./.env

    redis:
        image: redis:7.2.1-alpine3.18
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redisDB:/data
volumes:
    progresDB:
    redisDB:
